// ISO 3166-1 numeric codes match world-atlas Natural Earth feature IDs.
// `iso2` is the ISO 3166-1 alpha-2 code, used for flag emojis (regional indicators).
// `capital` is the country's primary/official capital (de jure where applicable).
// `borders` lists ISO-2 codes of land-bordering neighbors (CIA World Factbook based).
export type Continent =
  | "Africa"
  | "Asia"
  | "Europe"
  | "North America"
  | "South America"
  | "Oceania"
  | "Antarctica";

export interface Country {
  id: string;        // ISO 3166-1 numeric, zero-padded
  iso2: string;      // ISO 3166-1 alpha-2
  name: string;
  capital: string;
  continent: Continent;
  borders: string[]; // iso2 codes
}

export const countries: Country[] = [
  { id: "004", iso2: "AF", name: "Afghanistan", capital: "Kabul", continent: "Asia", borders: ["IR","PK","TM","UZ","TJ","CN"] },
  { id: "008", iso2: "AL", name: "Albania", capital: "Tirana", continent: "Europe", borders: ["ME","XK","MK","GR"] },
  { id: "012", iso2: "DZ", name: "Algeria", capital: "Algiers", continent: "Africa", borders: ["TN","LY","NE","ML","MR","EH","MA"] },
  { id: "024", iso2: "AO", name: "Angola", capital: "Luanda", continent: "Africa", borders: ["CG","CD","ZM","NA"] },
  { id: "032", iso2: "AR", name: "Argentina", capital: "Buenos Aires", continent: "South America", borders: ["BO","BR","CL","PY","UY"] },
  { id: "051", iso2: "AM", name: "Armenia", capital: "Yerevan", continent: "Asia", borders: ["AZ","GE","IR","TR"] },
  { id: "036", iso2: "AU", name: "Australia", capital: "Canberra", continent: "Oceania", borders: [] },
  { id: "040", iso2: "AT", name: "Austria", capital: "Vienna", continent: "Europe", borders: ["CZ","DE","HU","IT","LI","SK","SI","CH"] },
  { id: "031", iso2: "AZ", name: "Azerbaijan", capital: "Baku", continent: "Asia", borders: ["AM","GE","IR","RU","TR"] },
  { id: "044", iso2: "BS", name: "Bahamas", capital: "Nassau", continent: "North America", borders: [] },
  { id: "048", iso2: "BH", name: "Bahrain", capital: "Manama", continent: "Asia", borders: [] },
  { id: "050", iso2: "BD", name: "Bangladesh", capital: "Dhaka", continent: "Asia", borders: ["MM","IN"] },
  { id: "052", iso2: "BB", name: "Barbados", capital: "Bridgetown", continent: "North America", borders: [] },
  { id: "112", iso2: "BY", name: "Belarus", capital: "Minsk", continent: "Europe", borders: ["LV","LT","PL","RU","UA"] },
  { id: "056", iso2: "BE", name: "Belgium", capital: "Brussels", continent: "Europe", borders: ["FR","DE","LU","NL"] },
  { id: "084", iso2: "BZ", name: "Belize", capital: "Belmopan", continent: "North America", borders: ["GT","MX"] },
  { id: "204", iso2: "BJ", name: "Benin", capital: "Porto-Novo", continent: "Africa", borders: ["BF","NE","NG","TG"] },
  { id: "064", iso2: "BT", name: "Bhutan", capital: "Thimphu", continent: "Asia", borders: ["CN","IN"] },
  { id: "068", iso2: "BO", name: "Bolivia", capital: "Sucre", continent: "South America", borders: ["AR","BR","CL","PY","PE"] },
  { id: "070", iso2: "BA", name: "Bosnia and Herzegovina", capital: "Sarajevo", continent: "Europe", borders: ["HR","ME","RS"] },
  { id: "072", iso2: "BW", name: "Botswana", capital: "Gaborone", continent: "Africa", borders: ["NA","ZA","ZM","ZW"] },
  { id: "076", iso2: "BR", name: "Brazil", capital: "Brasília", continent: "South America", borders: ["AR","BO","CO","GF","GY","PY","PE","SR","UY","VE"] },
  { id: "096", iso2: "BN", name: "Brunei", capital: "Bandar Seri Begawan", continent: "Asia", borders: ["MY"] },
  { id: "100", iso2: "BG", name: "Bulgaria", capital: "Sofia", continent: "Europe", borders: ["GR","MK","RO","RS","TR"] },
  { id: "854", iso2: "BF", name: "Burkina Faso", capital: "Ouagadougou", continent: "Africa", borders: ["BJ","CI","GH","ML","NE","TG"] },
  { id: "108", iso2: "BI", name: "Burundi", capital: "Gitega", continent: "Africa", borders: ["CD","RW","TZ"] },
  { id: "116", iso2: "KH", name: "Cambodia", capital: "Phnom Penh", continent: "Asia", borders: ["LA","TH","VN"] },
  { id: "120", iso2: "CM", name: "Cameroon", capital: "Yaoundé", continent: "Africa", borders: ["CF","TD","CG","GQ","GA","NG"] },
  { id: "124", iso2: "CA", name: "Canada", capital: "Ottawa", continent: "North America", borders: ["US"] },
  { id: "140", iso2: "CF", name: "Central African Republic", capital: "Bangui", continent: "Africa", borders: ["CM","TD","CD","CG","SS","SD"] },
  { id: "148", iso2: "TD", name: "Chad", capital: "N'Djamena", continent: "Africa", borders: ["CM","CF","LY","NE","NG","SD"] },
  { id: "152", iso2: "CL", name: "Chile", capital: "Santiago", continent: "South America", borders: ["AR","BO","PE"] },
  { id: "156", iso2: "CN", name: "China", capital: "Beijing", continent: "Asia", borders: ["AF","BT","MM","IN","KZ","KG","LA","MN","NP","KP","PK","RU","TJ","VN"] },
  { id: "170", iso2: "CO", name: "Colombia", capital: "Bogotá", continent: "South America", borders: ["BR","EC","PA","PE","VE"] },
  { id: "174", iso2: "KM", name: "Comoros", capital: "Moroni", continent: "Africa", borders: [] },
  { id: "178", iso2: "CG", name: "Republic of the Congo", capital: "Brazzaville", continent: "Africa", borders: ["AO","CM","CF","CD","GA"] },
  { id: "180", iso2: "CD", name: "Democratic Republic of the Congo", capital: "Kinshasa", continent: "Africa", borders: ["AO","BI","CF","CG","RW","SS","TZ","UG","ZM"] },
  { id: "188", iso2: "CR", name: "Costa Rica", capital: "San José", continent: "North America", borders: ["NI","PA"] },
  { id: "384", iso2: "CI", name: "Ivory Coast", capital: "Yamoussoukro", continent: "Africa", borders: ["BF","GH","GN","LR","ML"] },
  { id: "191", iso2: "HR", name: "Croatia", capital: "Zagreb", continent: "Europe", borders: ["BA","HU","ME","RS","SI"] },
  { id: "192", iso2: "CU", name: "Cuba", capital: "Havana", continent: "North America", borders: [] },
  { id: "196", iso2: "CY", name: "Cyprus", capital: "Nicosia", continent: "Europe", borders: [] },
  { id: "203", iso2: "CZ", name: "Czech Republic", capital: "Prague", continent: "Europe", borders: ["AT","DE","PL","SK"] },
  { id: "208", iso2: "DK", name: "Denmark", capital: "Copenhagen", continent: "Europe", borders: ["DE"] },
  { id: "262", iso2: "DJ", name: "Djibouti", capital: "Djibouti", continent: "Africa", borders: ["ER","ET","SO"] },
  { id: "212", iso2: "DM", name: "Dominica", capital: "Roseau", continent: "North America", borders: [] },
  { id: "214", iso2: "DO", name: "Dominican Republic", capital: "Santo Domingo", continent: "North America", borders: ["HT"] },
  { id: "218", iso2: "EC", name: "Ecuador", capital: "Quito", continent: "South America", borders: ["CO","PE"] },
  { id: "818", iso2: "EG", name: "Egypt", capital: "Cairo", continent: "Africa", borders: ["IL","LY","SD"] },
  { id: "222", iso2: "SV", name: "El Salvador", capital: "San Salvador", continent: "North America", borders: ["GT","HN"] },
  { id: "226", iso2: "GQ", name: "Equatorial Guinea", capital: "Malabo", continent: "Africa", borders: ["CM","GA"] },
  { id: "232", iso2: "ER", name: "Eritrea", capital: "Asmara", continent: "Africa", borders: ["DJ","ET","SD"] },
  { id: "233", iso2: "EE", name: "Estonia", capital: "Tallinn", continent: "Europe", borders: ["LV","RU"] },
  { id: "748", iso2: "SZ", name: "Eswatini", capital: "Mbabane", continent: "Africa", borders: ["MZ","ZA"] },
  { id: "231", iso2: "ET", name: "Ethiopia", capital: "Addis Ababa", continent: "Africa", borders: ["DJ","ER","KE","SO","SS","SD"] },
  { id: "242", iso2: "FJ", name: "Fiji", capital: "Suva", continent: "Oceania", borders: [] },
  { id: "246", iso2: "FI", name: "Finland", capital: "Helsinki", continent: "Europe", borders: ["NO","SE","RU"] },
  { id: "250", iso2: "FR", name: "France", capital: "Paris", continent: "Europe", borders: ["AD","BE","DE","IT","LU","MC","ES","CH"] },
  { id: "266", iso2: "GA", name: "Gabon", capital: "Libreville", continent: "Africa", borders: ["CM","CG","GQ"] },
  { id: "270", iso2: "GM", name: "Gambia", capital: "Banjul", continent: "Africa", borders: ["SN"] },
  { id: "268", iso2: "GE", name: "Georgia", capital: "Tbilisi", continent: "Asia", borders: ["AM","AZ","RU","TR"] },
  { id: "276", iso2: "DE", name: "Germany", capital: "Berlin", continent: "Europe", borders: ["AT","BE","CZ","DK","FR","LU","NL","PL","CH"] },
  { id: "288", iso2: "GH", name: "Ghana", capital: "Accra", continent: "Africa", borders: ["BF","CI","TG"] },
  { id: "300", iso2: "GR", name: "Greece", capital: "Athens", continent: "Europe", borders: ["AL","BG","TR","MK"] },
  { id: "308", iso2: "GD", name: "Grenada", capital: "Saint George's", continent: "North America", borders: [] },
  { id: "320", iso2: "GT", name: "Guatemala", capital: "Guatemala City", continent: "North America", borders: ["BZ","SV","HN","MX"] },
  { id: "324", iso2: "GN", name: "Guinea", capital: "Conakry", continent: "Africa", borders: ["CI","GW","LR","ML","SN","SL"] },
  { id: "624", iso2: "GW", name: "Guinea-Bissau", capital: "Bissau", continent: "Africa", borders: ["GN","SN"] },
  { id: "328", iso2: "GY", name: "Guyana", capital: "Georgetown", continent: "South America", borders: ["BR","SR","VE"] },
  { id: "332", iso2: "HT", name: "Haiti", capital: "Port-au-Prince", continent: "North America", borders: ["DO"] },
  { id: "340", iso2: "HN", name: "Honduras", capital: "Tegucigalpa", continent: "North America", borders: ["GT","SV","NI"] },
  { id: "348", iso2: "HU", name: "Hungary", capital: "Budapest", continent: "Europe", borders: ["AT","HR","RO","RS","SK","SI","UA"] },
  { id: "352", iso2: "IS", name: "Iceland", capital: "Reykjavík", continent: "Europe", borders: [] },
  { id: "356", iso2: "IN", name: "India", capital: "New Delhi", continent: "Asia", borders: ["BD","BT","MM","CN","NP","PK"] },
  { id: "360", iso2: "ID", name: "Indonesia", capital: "Jakarta", continent: "Asia", borders: ["TL","MY","PG"] },
  { id: "364", iso2: "IR", name: "Iran", capital: "Tehran", continent: "Asia", borders: ["AF","AM","AZ","IQ","PK","TR","TM"] },
  { id: "368", iso2: "IQ", name: "Iraq", capital: "Baghdad", continent: "Asia", borders: ["IR","JO","KW","SA","SY","TR"] },
  { id: "372", iso2: "IE", name: "Ireland", capital: "Dublin", continent: "Europe", borders: ["GB"] },
  { id: "376", iso2: "IL", name: "Israel", capital: "Jerusalem", continent: "Asia", borders: ["EG","JO","LB","SY","PS"] },
  { id: "380", iso2: "IT", name: "Italy", capital: "Rome", continent: "Europe", borders: ["AT","FR","SM","SI","CH","VA"] },
  { id: "388", iso2: "JM", name: "Jamaica", capital: "Kingston", continent: "North America", borders: [] },
  { id: "392", iso2: "JP", name: "Japan", capital: "Tokyo", continent: "Asia", borders: [] },
  { id: "400", iso2: "JO", name: "Jordan", capital: "Amman", continent: "Asia", borders: ["IQ","IL","SA","SY","PS"] },
  { id: "398", iso2: "KZ", name: "Kazakhstan", capital: "Astana", continent: "Asia", borders: ["CN","KG","RU","TM","UZ"] },
  { id: "404", iso2: "KE", name: "Kenya", capital: "Nairobi", continent: "Africa", borders: ["ET","SO","SS","TZ","UG"] },
  { id: "296", iso2: "KI", name: "Kiribati", capital: "Tarawa", continent: "Oceania", borders: [] },
  { id: "408", iso2: "KP", name: "North Korea", capital: "Pyongyang", continent: "Asia", borders: ["CN","KR","RU"] },
  { id: "410", iso2: "KR", name: "South Korea", capital: "Seoul", continent: "Asia", borders: ["KP"] },
  { id: "983", iso2: "XK", name: "Kosovo", capital: "Pristina", continent: "Europe", borders: ["AL","MK","ME","RS"] },
  { id: "414", iso2: "KW", name: "Kuwait", capital: "Kuwait City", continent: "Asia", borders: ["IQ","SA"] },
  { id: "417", iso2: "KG", name: "Kyrgyzstan", capital: "Bishkek", continent: "Asia", borders: ["CN","KZ","TJ","UZ"] },
  { id: "418", iso2: "LA", name: "Laos", capital: "Vientiane", continent: "Asia", borders: ["MM","KH","CN","TH","VN"] },
  { id: "428", iso2: "LV", name: "Latvia", capital: "Riga", continent: "Europe", borders: ["BY","EE","LT","RU"] },
  { id: "422", iso2: "LB", name: "Lebanon", capital: "Beirut", continent: "Asia", borders: ["IL","SY"] },
  { id: "426", iso2: "LS", name: "Lesotho", capital: "Maseru", continent: "Africa", borders: ["ZA"] },
  { id: "430", iso2: "LR", name: "Liberia", capital: "Monrovia", continent: "Africa", borders: ["GN","CI","SL"] },
  { id: "434", iso2: "LY", name: "Libya", capital: "Tripoli", continent: "Africa", borders: ["DZ","TD","EG","NE","SD","TN"] },
  { id: "438", iso2: "LI", name: "Liechtenstein", capital: "Vaduz", continent: "Europe", borders: ["AT","CH"] },
  { id: "440", iso2: "LT", name: "Lithuania", capital: "Vilnius", continent: "Europe", borders: ["BY","LV","PL","RU"] },
  { id: "442", iso2: "LU", name: "Luxembourg", capital: "Luxembourg", continent: "Europe", borders: ["BE","FR","DE"] },
  { id: "807", iso2: "MK", name: "North Macedonia", capital: "Skopje", continent: "Europe", borders: ["AL","BG","GR","XK","RS"] },
  { id: "450", iso2: "MG", name: "Madagascar", capital: "Antananarivo", continent: "Africa", borders: [] },
  { id: "454", iso2: "MW", name: "Malawi", capital: "Lilongwe", continent: "Africa", borders: ["MZ","TZ","ZM"] },
  { id: "458", iso2: "MY", name: "Malaysia", capital: "Kuala Lumpur", continent: "Asia", borders: ["BN","ID","TH"] },
  { id: "462", iso2: "MV", name: "Maldives", capital: "Malé", continent: "Asia", borders: [] },
  { id: "466", iso2: "ML", name: "Mali", capital: "Bamako", continent: "Africa", borders: ["DZ","BF","GN","CI","MR","NE","SN"] },
  { id: "470", iso2: "MT", name: "Malta", capital: "Valletta", continent: "Europe", borders: [] },
  { id: "584", iso2: "MH", name: "Marshall Islands", capital: "Majuro", continent: "Oceania", borders: [] },
  { id: "478", iso2: "MR", name: "Mauritania", capital: "Nouakchott", continent: "Africa", borders: ["DZ","ML","SN","EH"] },
  { id: "480", iso2: "MU", name: "Mauritius", capital: "Port Louis", continent: "Africa", borders: [] },
  { id: "484", iso2: "MX", name: "Mexico", capital: "Mexico City", continent: "North America", borders: ["BZ","GT","US"] },
  { id: "583", iso2: "FM", name: "Micronesia", capital: "Palikir", continent: "Oceania", borders: [] },
  { id: "498", iso2: "MD", name: "Moldova", capital: "Chișinău", continent: "Europe", borders: ["RO","UA"] },
  { id: "492", iso2: "MC", name: "Monaco", capital: "Monaco", continent: "Europe", borders: ["FR"] },
  { id: "496", iso2: "MN", name: "Mongolia", capital: "Ulaanbaatar", continent: "Asia", borders: ["CN","RU"] },
  { id: "499", iso2: "ME", name: "Montenegro", capital: "Podgorica", continent: "Europe", borders: ["AL","BA","HR","XK","RS"] },
  { id: "504", iso2: "MA", name: "Morocco", capital: "Rabat", continent: "Africa", borders: ["DZ","EH","ES"] },
  { id: "508", iso2: "MZ", name: "Mozambique", capital: "Maputo", continent: "Africa", borders: ["MW","ZA","SZ","TZ","ZM","ZW"] },
  { id: "104", iso2: "MM", name: "Myanmar", capital: "Naypyidaw", continent: "Asia", borders: ["BD","CN","IN","LA","TH"] },
  { id: "516", iso2: "NA", name: "Namibia", capital: "Windhoek", continent: "Africa", borders: ["AO","BW","ZA","ZM"] },
  { id: "520", iso2: "NR", name: "Nauru", capital: "Yaren", continent: "Oceania", borders: [] },
  { id: "524", iso2: "NP", name: "Nepal", capital: "Kathmandu", continent: "Asia", borders: ["CN","IN"] },
  { id: "528", iso2: "NL", name: "Netherlands", capital: "Amsterdam", continent: "Europe", borders: ["BE","DE"] },
  { id: "554", iso2: "NZ", name: "New Zealand", capital: "Wellington", continent: "Oceania", borders: [] },
  { id: "558", iso2: "NI", name: "Nicaragua", capital: "Managua", continent: "North America", borders: ["CR","HN"] },
  { id: "562", iso2: "NE", name: "Niger", capital: "Niamey", continent: "Africa", borders: ["DZ","BJ","BF","TD","LY","ML","NG"] },
  { id: "566", iso2: "NG", name: "Nigeria", capital: "Abuja", continent: "Africa", borders: ["BJ","CM","TD","NE"] },
  { id: "578", iso2: "NO", name: "Norway", capital: "Oslo", continent: "Europe", borders: ["FI","SE","RU"] },
  { id: "512", iso2: "OM", name: "Oman", capital: "Muscat", continent: "Asia", borders: ["SA","AE","YE"] },
  { id: "586", iso2: "PK", name: "Pakistan", capital: "Islamabad", continent: "Asia", borders: ["AF","CN","IN","IR"] },
  { id: "585", iso2: "PW", name: "Palau", capital: "Ngerulmud", continent: "Oceania", borders: [] },
  { id: "275", iso2: "PS", name: "Palestine", capital: "Ramallah", continent: "Asia", borders: ["IL","JO","EG"] },
  { id: "591", iso2: "PA", name: "Panama", capital: "Panama City", continent: "North America", borders: ["CO","CR"] },
  { id: "598", iso2: "PG", name: "Papua New Guinea", capital: "Port Moresby", continent: "Oceania", borders: ["ID"] },
  { id: "600", iso2: "PY", name: "Paraguay", capital: "Asunción", continent: "South America", borders: ["AR","BO","BR"] },
  { id: "604", iso2: "PE", name: "Peru", capital: "Lima", continent: "South America", borders: ["BO","BR","CL","CO","EC"] },
  { id: "608", iso2: "PH", name: "Philippines", capital: "Manila", continent: "Asia", borders: [] },
  { id: "616", iso2: "PL", name: "Poland", capital: "Warsaw", continent: "Europe", borders: ["BY","CZ","DE","LT","RU","SK","UA"] },
  { id: "620", iso2: "PT", name: "Portugal", capital: "Lisbon", continent: "Europe", borders: ["ES"] },
  { id: "634", iso2: "QA", name: "Qatar", capital: "Doha", continent: "Asia", borders: ["SA"] },
  { id: "642", iso2: "RO", name: "Romania", capital: "Bucharest", continent: "Europe", borders: ["BG","HU","MD","RS","UA"] },
  { id: "643", iso2: "RU", name: "Russia", capital: "Moscow", continent: "Europe", borders: ["AZ","BY","CN","EE","FI","GE","KZ","KP","LV","LT","MN","NO","PL","UA"] },
  { id: "646", iso2: "RW", name: "Rwanda", capital: "Kigali", continent: "Africa", borders: ["BI","CD","TZ","UG"] },
  { id: "659", iso2: "KN", name: "Saint Kitts and Nevis", capital: "Basseterre", continent: "North America", borders: [] },
  { id: "662", iso2: "LC", name: "Saint Lucia", capital: "Castries", continent: "North America", borders: [] },
  { id: "670", iso2: "VC", name: "Saint Vincent and the Grenadines", capital: "Kingstown", continent: "North America", borders: [] },
  { id: "882", iso2: "WS", name: "Samoa", capital: "Apia", continent: "Oceania", borders: [] },
  { id: "674", iso2: "SM", name: "San Marino", capital: "San Marino", continent: "Europe", borders: ["IT"] },
  { id: "678", iso2: "ST", name: "Sao Tome and Principe", capital: "São Tomé", continent: "Africa", borders: [] },
  { id: "682", iso2: "SA", name: "Saudi Arabia", capital: "Riyadh", continent: "Asia", borders: ["IQ","JO","KW","OM","QA","AE","YE"] },
  { id: "686", iso2: "SN", name: "Senegal", capital: "Dakar", continent: "Africa", borders: ["GM","GN","GW","ML","MR"] },
  { id: "688", iso2: "RS", name: "Serbia", capital: "Belgrade", continent: "Europe", borders: ["BA","BG","HR","HU","XK","MK","ME","RO"] },
  { id: "690", iso2: "SC", name: "Seychelles", capital: "Victoria", continent: "Africa", borders: [] },
  { id: "694", iso2: "SL", name: "Sierra Leone", capital: "Freetown", continent: "Africa", borders: ["GN","LR"] },
  { id: "702", iso2: "SG", name: "Singapore", capital: "Singapore", continent: "Asia", borders: [] },
  { id: "703", iso2: "SK", name: "Slovakia", capital: "Bratislava", continent: "Europe", borders: ["AT","CZ","HU","PL","UA"] },
  { id: "705", iso2: "SI", name: "Slovenia", capital: "Ljubljana", continent: "Europe", borders: ["AT","HR","IT","HU"] },
  { id: "090", iso2: "SB", name: "Solomon Islands", capital: "Honiara", continent: "Oceania", borders: [] },
  { id: "706", iso2: "SO", name: "Somalia", capital: "Mogadishu", continent: "Africa", borders: ["DJ","ET","KE"] },
  { id: "710", iso2: "ZA", name: "South Africa", capital: "Pretoria", continent: "Africa", borders: ["BW","LS","MZ","NA","SZ","ZW"] },
  { id: "728", iso2: "SS", name: "South Sudan", capital: "Juba", continent: "Africa", borders: ["CF","CD","ET","KE","SD","UG"] },
  { id: "724", iso2: "ES", name: "Spain", capital: "Madrid", continent: "Europe", borders: ["AD","FR","PT","MA"] },
  { id: "144", iso2: "LK", name: "Sri Lanka", capital: "Colombo", continent: "Asia", borders: [] },
  { id: "729", iso2: "SD", name: "Sudan", capital: "Khartoum", continent: "Africa", borders: ["CF","TD","EG","ER","ET","LY","SS"] },
  { id: "740", iso2: "SR", name: "Suriname", capital: "Paramaribo", continent: "South America", borders: ["BR","GF","GY"] },
  { id: "752", iso2: "SE", name: "Sweden", capital: "Stockholm", continent: "Europe", borders: ["FI","NO"] },
  { id: "756", iso2: "CH", name: "Switzerland", capital: "Bern", continent: "Europe", borders: ["AT","FR","IT","LI","DE"] },
  { id: "760", iso2: "SY", name: "Syria", capital: "Damascus", continent: "Asia", borders: ["IQ","IL","JO","LB","TR"] },
  { id: "158", iso2: "TW", name: "Taiwan", capital: "Taipei", continent: "Asia", borders: [] },
  { id: "762", iso2: "TJ", name: "Tajikistan", capital: "Dushanbe", continent: "Asia", borders: ["AF","CN","KG","UZ"] },
  { id: "834", iso2: "TZ", name: "Tanzania", capital: "Dodoma", continent: "Africa", borders: ["BI","CD","KE","MW","MZ","RW","UG","ZM"] },
  { id: "764", iso2: "TH", name: "Thailand", capital: "Bangkok", continent: "Asia", borders: ["MM","KH","LA","MY"] },
  { id: "626", iso2: "TL", name: "Timor-Leste", capital: "Dili", continent: "Asia", borders: ["ID"] },
  { id: "768", iso2: "TG", name: "Togo", capital: "Lomé", continent: "Africa", borders: ["BJ","BF","GH"] },
  { id: "776", iso2: "TO", name: "Tonga", capital: "Nukuʻalofa", continent: "Oceania", borders: [] },
  { id: "780", iso2: "TT", name: "Trinidad and Tobago", capital: "Port of Spain", continent: "North America", borders: [] },
  { id: "788", iso2: "TN", name: "Tunisia", capital: "Tunis", continent: "Africa", borders: ["DZ","LY"] },
  { id: "792", iso2: "TR", name: "Turkey", capital: "Ankara", continent: "Asia", borders: ["AM","AZ","BG","GE","GR","IR","IQ","SY"] },
  { id: "795", iso2: "TM", name: "Turkmenistan", capital: "Ashgabat", continent: "Asia", borders: ["AF","IR","KZ","UZ"] },
  { id: "798", iso2: "TV", name: "Tuvalu", capital: "Funafuti", continent: "Oceania", borders: [] },
  { id: "800", iso2: "UG", name: "Uganda", capital: "Kampala", continent: "Africa", borders: ["CD","KE","RW","SS","TZ"] },
  { id: "804", iso2: "UA", name: "Ukraine", capital: "Kyiv", continent: "Europe", borders: ["BY","HU","MD","PL","RO","RU","SK"] },
  { id: "784", iso2: "AE", name: "United Arab Emirates", capital: "Abu Dhabi", continent: "Asia", borders: ["OM","SA"] },
  { id: "826", iso2: "GB", name: "United Kingdom", capital: "London", continent: "Europe", borders: ["IE"] },
  { id: "840", iso2: "US", name: "United States", capital: "Washington, D.C.", continent: "North America", borders: ["CA","MX"] },
  { id: "858", iso2: "UY", name: "Uruguay", capital: "Montevideo", continent: "South America", borders: ["AR","BR"] },
  { id: "860", iso2: "UZ", name: "Uzbekistan", capital: "Tashkent", continent: "Asia", borders: ["AF","KZ","KG","TJ","TM"] },
  { id: "548", iso2: "VU", name: "Vanuatu", capital: "Port Vila", continent: "Oceania", borders: [] },
  { id: "336", iso2: "VA", name: "Vatican City", capital: "Vatican City", continent: "Europe", borders: ["IT"] },
  { id: "862", iso2: "VE", name: "Venezuela", capital: "Caracas", continent: "South America", borders: ["BR","CO","GY"] },
  { id: "704", iso2: "VN", name: "Vietnam", capital: "Hanoi", continent: "Asia", borders: ["KH","CN","LA"] },
  { id: "887", iso2: "YE", name: "Yemen", capital: "Sana'a", continent: "Asia", borders: ["OM","SA"] },
  { id: "894", iso2: "ZM", name: "Zambia", capital: "Lusaka", continent: "Africa", borders: ["AO","CD","MW","MZ","NA","TZ","ZW"] },
  { id: "716", iso2: "ZW", name: "Zimbabwe", capital: "Harare", continent: "Africa", borders: ["BW","MZ","ZA","ZM"] },
];

export const countryByIso2: Record<string, Country> = Object.fromEntries(
  countries.map((c) => [c.iso2, c]),
);

/** Convert an ISO-2 code to its flag emoji using regional indicator symbols. */
export function flagEmoji(iso2: string): string {
  if (iso2.length !== 2) return "🏳️";
  const codePoints = iso2
    .toUpperCase()
    .split("")
    .map((c) => 127397 + c.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}
