export type EmpireDifficulty = "easy" | "medium" | "hard";

export interface EmpireEntry {
  id: string;
  name: string;
  era: string;
  description: string;
  difficulty: EmpireDifficulty;
  region: string;
  countries: string[];
  notes?: string;
}

// Rule of inclusion: a modern country counts when a meaningful portion of its
// current territory was controlled, settled, or incorporated at or near peak.
export const empires: EmpireEntry[] = [
  {
    id: "roman-empire",
    name: "Roman Empire",
    era: "c. 117 CE",
    description: "The Mediterranean empire at its Trajanic height.",
    difficulty: "easy",
    region: "Mediterranean",
    countries: [
      "GB",
      "PT",
      "ES",
      "FR",
      "BE",
      "NL",
      "DE",
      "CH",
      "AT",
      "IT",
      "SI",
      "HR",
      "BA",
      "RS",
      "ME",
      "XK",
      "AL",
      "MK",
      "GR",
      "BG",
      "RO",
      "TR",
      "CY",
      "SY",
      "LB",
      "IL",
      "PS",
      "JO",
      "EG",
      "LY",
      "TN",
      "DZ",
      "MA",
    ],
    notes: "Includes provinces and major frontier territories, not every temporary campaign zone.",
  },
  {
    id: "byzantine-empire",
    name: "Byzantine Empire",
    era: "c. 565 CE",
    description: "The eastern Roman Empire under Justinian after major reconquests.",
    difficulty: "medium",
    region: "Eastern Mediterranean",
    countries: [
      "IT",
      "VA",
      "SM",
      "GR",
      "TR",
      "CY",
      "SY",
      "LB",
      "IL",
      "PS",
      "JO",
      "EG",
      "LY",
      "TN",
      "DZ",
      "AL",
      "MK",
      "BG",
      "RS",
      "BA",
      "HR",
      "ME",
    ],
    notes: "Uses Justinian's maximum extent; later Byzantine borders were much smaller.",
  },
  {
    id: "ottoman-empire",
    name: "Ottoman Empire",
    era: "c. 1683 CE",
    description:
      "A transcontinental empire linking Anatolia, the Balkans, North Africa, and the Middle East.",
    difficulty: "easy",
    region: "Islamic world",
    countries: [
      "TR",
      "GR",
      "BG",
      "RO",
      "RS",
      "BA",
      "HR",
      "HU",
      "ME",
      "XK",
      "AL",
      "MK",
      "CY",
      "SY",
      "LB",
      "IL",
      "PS",
      "JO",
      "SA",
      "IQ",
      "KW",
      "EG",
      "LY",
      "TN",
      "DZ",
      "YE",
      "GE",
      "AM",
      "AZ",
      "UA",
      "MD",
    ],
    notes: "Includes vassal or strongly controlled zones where Ottoman power was durable.",
  },
  {
    id: "mongol-empire",
    name: "Mongol Empire",
    era: "13th century",
    description: "The largest contiguous land empire in history.",
    difficulty: "easy",
    region: "Eurasia",
    countries: [
      "MN",
      "CN",
      "KP",
      "KR",
      "RU",
      "KZ",
      "KG",
      "TJ",
      "UZ",
      "TM",
      "AF",
      "PK",
      "IR",
      "IQ",
      "AZ",
      "AM",
      "GE",
      "TR",
      "UA",
      "BY",
      "MD",
      "RO",
      "BG",
      "HU",
      "PL",
    ],
    notes: "Represents the united empire and early successor khanates at maximum reach.",
  },
  {
    id: "british-empire",
    name: "British Empire",
    era: "c. 1920 CE",
    description: "A global maritime empire at its post-World War I territorial peak.",
    difficulty: "easy",
    region: "Global empires",
    countries: [
      "GB",
      "IE",
      "CA",
      "US",
      "BZ",
      "GY",
      "TT",
      "JM",
      "BS",
      "BB",
      "GD",
      "LC",
      "VC",
      "KN",
      "NG",
      "GH",
      "SL",
      "GM",
      "EG",
      "SD",
      "SS",
      "KE",
      "UG",
      "TZ",
      "MW",
      "ZM",
      "ZW",
      "BW",
      "ZA",
      "LS",
      "SZ",
      "IN",
      "PK",
      "BD",
      "LK",
      "MM",
      "MY",
      "SG",
      "BN",
      "AU",
      "NZ",
      "FJ",
      "PG",
    ],
    notes: "Includes colonies, dominions, mandates, and major protectorates.",
  },
  {
    id: "spanish-empire",
    name: "Spanish Empire",
    era: "16th-18th centuries",
    description: "A vast Atlantic and Pacific empire ruled from Spain.",
    difficulty: "easy",
    region: "Global empires",
    countries: [
      "ES",
      "MX",
      "GT",
      "BZ",
      "SV",
      "HN",
      "NI",
      "CR",
      "PA",
      "CU",
      "DO",
      "CO",
      "VE",
      "EC",
      "PE",
      "BO",
      "CL",
      "AR",
      "PY",
      "UY",
      "US",
      "PH",
      "GQ",
      "MA",
    ],
    notes:
      "Modern Belize and parts of the United States are included for meaningful Spanish imperial presence.",
  },
  {
    id: "portuguese-empire",
    name: "Portuguese Empire",
    era: "16th-20th centuries",
    description:
      "A long-lived oceanic empire linking the Atlantic, Africa, India, and Southeast Asia.",
    difficulty: "medium",
    region: "Global empires",
    countries: ["PT", "BR", "AO", "MZ", "GW", "ST", "IN", "LK", "MY", "ID", "TL", "CN", "MA"],
    notes: "Includes major colonies and trading enclaves with durable Portuguese rule.",
  },
  {
    id: "french-colonial-empire",
    name: "French Colonial Empire",
    era: "19th-20th centuries",
    description: "France's modern colonial empire across Africa, Asia, Oceania, and the Americas.",
    difficulty: "medium",
    region: "Global empires",
    countries: [
      "FR",
      "CA",
      "US",
      "HT",
      "MA",
      "DZ",
      "TN",
      "MR",
      "ML",
      "SN",
      "GN",
      "CI",
      "BF",
      "NE",
      "BJ",
      "TD",
      "CF",
      "CG",
      "GA",
      "DJ",
      "MG",
      "KM",
      "VN",
      "LA",
      "KH",
      "VU",
    ],
    notes: "Uses major colonies and protectorates, not every tiny island possession.",
  },
  {
    id: "dutch-colonial-empire",
    name: "Dutch Colonial Empire",
    era: "17th-20th centuries",
    description: "A commercial empire built through the VOC and Dutch Atlantic ventures.",
    difficulty: "medium",
    region: "Global empires",
    countries: ["NL", "ID", "LK", "TW", "ZA", "GH", "SR", "GY", "US", "MY"],
    notes: "Includes meaningful colonies, fortified settlements, and plantation colonies.",
  },
  {
    id: "russian-empire",
    name: "Russian Empire",
    era: "c. 1914 CE",
    description: "The Romanov empire stretching from Eastern Europe to the Pacific.",
    difficulty: "easy",
    region: "Eurasia",
    countries: [
      "RU",
      "FI",
      "EE",
      "LV",
      "LT",
      "BY",
      "UA",
      "MD",
      "PL",
      "GE",
      "AM",
      "AZ",
      "KZ",
      "UZ",
      "TM",
      "KG",
      "TJ",
      "MN",
    ],
    notes: "Includes the Grand Duchy of Finland and Congress Poland within the imperial system.",
  },
  {
    id: "soviet-union",
    name: "Soviet Union",
    era: "1922-1991",
    description: "The federal socialist state formed after the Russian Revolution.",
    difficulty: "easy",
    region: "Cold War",
    countries: [
      "RU",
      "UA",
      "BY",
      "MD",
      "EE",
      "LV",
      "LT",
      "GE",
      "AM",
      "AZ",
      "KZ",
      "UZ",
      "TM",
      "KG",
      "TJ",
    ],
  },
  {
    id: "qing-dynasty",
    name: "Qing Dynasty",
    era: "18th century",
    description: "China's last imperial dynasty at high Qing expansion.",
    difficulty: "medium",
    region: "China",
    countries: ["CN", "MN", "TW", "KZ", "KG", "TJ", "RU"],
    notes:
      "Includes Xinjiang, Tibet, Mongolia, Taiwan, and frontier areas mapped to modern states.",
  },
  {
    id: "han-dynasty",
    name: "Han Dynasty",
    era: "2nd century BCE-2nd century CE",
    description: "A formative Chinese dynasty that expanded into Central Asia, Korea, and Vietnam.",
    difficulty: "hard",
    region: "China",
    countries: ["CN", "KP", "KR", "VN", "MN", "KZ", "KG"],
    notes: "Includes protectorates and commanderies where Han control was substantial.",
  },
  {
    id: "tang-dynasty",
    name: "Tang Dynasty",
    era: "7th-8th centuries",
    description: "A cosmopolitan Chinese empire with deep Central Asian reach.",
    difficulty: "hard",
    region: "China",
    countries: ["CN", "MN", "KZ", "KG", "TJ", "UZ", "TM", "VN", "KP", "KR"],
    notes: "Represents Tang direct rule and protectorate control at or near peak.",
  },
  {
    id: "mughal-empire",
    name: "Mughal Empire",
    era: "c. 1707 CE",
    description: "A powerful early modern empire over much of South Asia.",
    difficulty: "easy",
    region: "India",
    countries: ["IN", "PK", "BD", "AF"],
    notes: "Afghanistan is included for Kabul and related frontier provinces.",
  },
  {
    id: "maurya-empire",
    name: "Maurya Empire",
    era: "c. 250 BCE",
    description: "The largest ancient empire in South Asian history.",
    difficulty: "medium",
    region: "India",
    countries: ["IN", "PK", "BD", "NP", "AF"],
    notes: "Sri Lanka was influenced by Ashoka but is not counted as incorporated territory here.",
  },
  {
    id: "gupta-empire",
    name: "Gupta Empire",
    era: "4th-5th centuries",
    description: "A classical North Indian empire associated with major cultural achievements.",
    difficulty: "hard",
    region: "India",
    countries: ["IN", "BD", "NP", "PK"],
    notes: "Uses core and major tributary zones at broad peak.",
  },
  {
    id: "achaemenid-persian-empire",
    name: "Achaemenid Persian Empire",
    era: "c. 500 BCE",
    description: "The first Persian Empire, stretching from Egypt to the Indus.",
    difficulty: "easy",
    region: "Ancient Near East",
    countries: ["IR", "IQ", "TR", "SY", "LB", "IL", "PS", "JO", "EG", "LY", "AM", "GE", "AZ"],
    notes: "Includes core Persian satrapies and major conquered regions at broad imperial peak.",
  },
  {
    id: "sasanian-empire",
    name: "Sasanian Empire",
    era: "6th-7th centuries",
    description: "The last pre-Islamic Persian empire and Rome's major eastern rival.",
    difficulty: "medium",
    region: "Ancient Near East",
    countries: [
      "IR",
      "IQ",
      "AZ",
      "AM",
      "GE",
      "TR",
      "SY",
      "LB",
      "IL",
      "PS",
      "JO",
      "EG",
      "PK",
      "AF",
      "TM",
      "UZ",
    ],
    notes: "Includes major conquests during the last Roman-Persian wars.",
  },
  {
    id: "abbasid-caliphate",
    name: "Abbasid Caliphate",
    era: "8th-9th centuries",
    description: "The Baghdad-centered caliphate during its early imperial height.",
    difficulty: "medium",
    region: "Islamic world",
    countries: [
      "IQ",
      "IR",
      "SY",
      "LB",
      "IL",
      "PS",
      "JO",
      "SA",
      "YE",
      "OM",
      "AE",
      "QA",
      "BH",
      "KW",
      "EG",
      "LY",
      "TN",
      "DZ",
      "MA",
      "AF",
      "PK",
      "TM",
      "UZ",
      "TJ",
      "KG",
      "TR",
    ],
    notes: "Later Abbasid authority varied widely; this uses early caliphal reach.",
  },
  {
    id: "umayyad-caliphate",
    name: "Umayyad Caliphate",
    era: "c. 750 CE",
    description: "The first great hereditary Islamic caliphate, from Iberia to Central Asia.",
    difficulty: "medium",
    region: "Islamic world",
    countries: [
      "ES",
      "PT",
      "MA",
      "DZ",
      "TN",
      "LY",
      "EG",
      "SD",
      "SA",
      "YE",
      "OM",
      "AE",
      "QA",
      "BH",
      "KW",
      "JO",
      "IL",
      "PS",
      "LB",
      "SY",
      "IQ",
      "IR",
      "AF",
      "PK",
      "TM",
      "UZ",
      "TJ",
      "KG",
      "TR",
      "AM",
      "AZ",
    ],
  },
  {
    id: "mali-empire",
    name: "Mali Empire",
    era: "14th century",
    description: "A wealthy West African empire known for gold trade and Mansa Musa.",
    difficulty: "medium",
    region: "Africa",
    countries: ["ML", "SN", "GM", "GN", "GW", "MR", "BF", "NE"],
    notes: "Modern countries reflect meaningful overlap with core and major provinces.",
  },
  {
    id: "songhai-empire",
    name: "Songhai Empire",
    era: "15th-16th centuries",
    description: "A major Sahelian empire centered on Gao and Timbuktu.",
    difficulty: "medium",
    region: "Africa",
    countries: ["ML", "NE", "NG", "BF", "BJ", "SN", "GN", "MR"],
  },
  {
    id: "ghana-empire",
    name: "Ghana Empire",
    era: "c. 1000 CE",
    description: "An early West African empire controlling Saharan gold trade routes.",
    difficulty: "hard",
    region: "Africa",
    countries: ["MR", "ML", "SN"],
    notes: "Not the same place as modern Ghana.",
  },
  {
    id: "ethiopian-empire",
    name: "Ethiopian Empire / Abyssinia",
    era: "medieval-20th century",
    description: "A highland empire in the Horn of Africa with long-lived Solomonic traditions.",
    difficulty: "medium",
    region: "Africa",
    countries: ["ET", "ER"],
    notes: "Includes Eritrean highlands and Red Sea territories at various periods.",
  },
  {
    id: "inca-empire",
    name: "Inca Empire",
    era: "c. 1530 CE",
    description: "The largest empire in pre-Columbian South America.",
    difficulty: "easy",
    region: "South America",
    countries: ["PE", "EC", "BO", "CL", "AR", "CO"],
  },
  {
    id: "aztec-empire",
    name: "Aztec Empire",
    era: "c. 1519 CE",
    description: "The Triple Alliance centered on Tenochtitlan in central Mexico.",
    difficulty: "easy",
    region: "Mesoamerica",
    countries: ["MX"],
  },
  {
    id: "maya-civilization-area",
    name: "Maya Civilization Area",
    era: "Classic and Postclassic periods",
    description: "The broader region of major Maya city-states and cultural settlement.",
    difficulty: "medium",
    region: "Mesoamerica",
    countries: ["MX", "GT", "BZ", "HN", "SV"],
    notes: "This is a civilization area rather than a single centralized empire.",
  },
  {
    id: "khmer-empire",
    name: "Khmer Empire",
    era: "12th century",
    description: "The Angkor-centered empire of mainland Southeast Asia.",
    difficulty: "medium",
    region: "Southeast Asia",
    countries: ["KH", "TH", "LA", "VN"],
    notes: "Includes major zones of imperial control and influence around Angkor.",
  },
  {
    id: "japanese-empire",
    name: "Japanese Empire",
    era: "1930s-1945",
    description: "Imperial Japan and its wartime empire in East and Southeast Asia.",
    difficulty: "medium",
    region: "East Asia",
    countries: [
      "JP",
      "KR",
      "KP",
      "CN",
      "TW",
      "MN",
      "MM",
      "TH",
      "LA",
      "KH",
      "VN",
      "MY",
      "SG",
      "ID",
      "PH",
      "PG",
    ],
    notes: "Includes occupied territories and puppet regimes at wartime peak.",
  },
  {
    id: "austro-hungarian-empire",
    name: "Austro-Hungarian Empire",
    era: "1867-1918",
    description: "The Habsburg Dual Monarchy in Central and Southeastern Europe.",
    difficulty: "easy",
    region: "Europe",
    countries: ["AT", "HU", "CZ", "SK", "SI", "HR", "BA", "RO", "PL", "UA", "IT", "RS"],
  },
  {
    id: "holy-roman-empire",
    name: "Holy Roman Empire",
    era: "c. 1000-1500 CE",
    description: "A loose imperial federation in central Europe.",
    difficulty: "hard",
    region: "Europe",
    countries: ["DE", "AT", "CZ", "NL", "BE", "LU", "CH", "LI", "SI", "IT", "FR", "PL"],
    notes: "Borders shifted for centuries; this uses meaningful recurring imperial territories.",
  },
  {
    id: "carolingian-empire",
    name: "Carolingian Empire",
    era: "c. 814 CE",
    description: "Charlemagne's empire across much of western and central Europe.",
    difficulty: "medium",
    region: "Europe",
    countries: ["FR", "DE", "IT", "BE", "NL", "LU", "CH", "AT", "SI", "HR", "ES"],
  },
  {
    id: "swedish-empire",
    name: "Swedish Empire",
    era: "17th century",
    description: "A Baltic empire during Sweden's age of great power.",
    difficulty: "hard",
    region: "Europe",
    countries: ["SE", "FI", "EE", "LV", "DE", "PL", "RU"],
  },
  {
    id: "srivijaya",
    name: "Srivijaya",
    era: "7th-13th centuries",
    description: "A maritime Buddhist thalassocracy controlling key Southeast Asian trade routes.",
    difficulty: "hard",
    region: "Southeast Asia",
    countries: ["ID", "MY", "SG", "TH"],
    notes: "Maritime power is approximated through major controlled and settled zones.",
  },
];
