export type TimelineDifficulty = "easy" | "medium" | "hard";
export type TimelineAnswer = "A" | "B";

export interface TimelineEvent {
  title: string;
  year: number;
  displayDate: string;
}

export interface TimelineQuestion {
  id: string;
  eventA: TimelineEvent;
  eventB: TimelineEvent;
  correctAnswer: TimelineAnswer;
  explanation: string;
  difficulty: TimelineDifficulty;
  era: string;
  region: string;
}

const question = (
  id: string,
  eventA: TimelineEvent,
  eventB: TimelineEvent,
  explanation: string,
  difficulty: TimelineDifficulty,
  era: string,
  region: string,
): TimelineQuestion => ({
  id,
  eventA,
  eventB,
  correctAnswer: eventA.year <= eventB.year ? "A" : "B",
  explanation,
  difficulty,
  era,
  region,
});

const e = (title: string, year: number, displayDate: string): TimelineEvent => ({
  title,
  year,
  displayDate,
});

export const timelineQuestions: TimelineQuestion[] = [
  question(
    "tr-001",
    e("Narmer traditionally unifies Upper and Lower Egypt", -3100, "c. 3100 BCE"),
    e("The Great Pyramid of Giza is completed", -2560, "c. 2560 BCE"),
    "Egyptian state formation came centuries before the Old Kingdom pyramid age.",
    "easy",
    "Ancient",
    "Egypt",
  ),
  question(
    "tr-002",
    e("Cuneiform writing develops in Sumer", -3200, "c. 3200 BCE"),
    e("Hammurabi issues his law code in Babylon", -1754, "c. 1754 BCE"),
    "Sumerian writing was already ancient by the time Hammurabi ruled Babylon.",
    "easy",
    "Ancient",
    "Ancient Near East",
  ),
  question(
    "tr-003",
    e("The Akkadian Empire rises under Sargon", -2334, "c. 2334 BCE"),
    e("The Hittites sack Babylon", -1595, "c. 1595 BCE"),
    "Sargon's Akkadian Empire belongs to the third millennium BCE, long before the Hittite raid on Babylon.",
    "medium",
    "Ancient",
    "Ancient Near East",
  ),
  question(
    "tr-004",
    e("The Indus city of Mohenjo-daro flourishes", -2500, "c. 2500 BCE"),
    e("The Maurya Empire is founded", -322, "322 BCE"),
    "The urban Indus civilization predates the Maurya Empire by more than two thousand years.",
    "easy",
    "Ancient",
    "India",
  ),
  question(
    "tr-005",
    e("Shang dynasty rule begins in China", -1600, "c. 1600 BCE"),
    e("Qin Shi Huang unifies China", -221, "221 BCE"),
    "The Shang dynasty came more than a millennium before Qin unification.",
    "easy",
    "Ancient",
    "China",
  ),
  question(
    "tr-006",
    e("The Olmec civilization emerges", -1500, "c. 1500 BCE"),
    e("Teotihuacan reaches its height", 450, "c. 450 CE"),
    "Olmec culture was an early Mesoamerican foundation, far earlier than Teotihuacan's classic period.",
    "medium",
    "Ancient",
    "Mesoamerica",
  ),
  question(
    "tr-007",
    e("The Code of Hammurabi is issued", -1754, "c. 1754 BCE"),
    e("The Hebrew Bible's Babylonian exile begins", -586, "586 BCE"),
    "Hammurabi's Babylonian law code predates the Babylonian exile by over a thousand years.",
    "medium",
    "Ancient",
    "Ancient Near East",
  ),
  question(
    "tr-008",
    e("New Kingdom Egypt begins", -1550, "c. 1550 BCE"),
    e("The Battle of Kadesh is fought", -1274, "c. 1274 BCE"),
    "The New Kingdom was already established before Ramesses II fought the Hittites at Kadesh.",
    "medium",
    "Ancient",
    "Egypt",
  ),
  question(
    "tr-009",
    e("The Trojan War is traditionally dated", -1180, "c. 1180 BCE"),
    e("The first Olympic Games are traditionally held", -776, "776 BCE"),
    "The legendary Trojan War setting comes centuries before the traditional first Olympics.",
    "easy",
    "Ancient",
    "Greece and Rome",
  ),
  question(
    "tr-010",
    e("The Zhou dynasty begins", -1046, "1046 BCE"),
    e("Confucius is born", -551, "551 BCE"),
    "Zhou rule began about five centuries before Confucius.",
    "easy",
    "Ancient",
    "China",
  ),
  question(
    "tr-011",
    e("Rome is traditionally founded", -753, "753 BCE"),
    e("The Roman Republic begins", -509, "509 BCE"),
    "Rome's traditional founding date comes before the monarchy was replaced by the Republic.",
    "easy",
    "Ancient",
    "Greece and Rome",
  ),
  question(
    "tr-012",
    e("The Assyrian Empire captures Israel's northern kingdom", -722, "722 BCE"),
    e("Cyrus the Great conquers Babylon", -539, "539 BCE"),
    "Assyria's conquest of Israel came before Persia replaced Babylon as the dominant regional power.",
    "medium",
    "Ancient",
    "Ancient Near East",
  ),
  question(
    "tr-013",
    e("Buddha is traditionally born", -563, "c. 563 BCE"),
    e("Alexander the Great enters India", -326, "326 BCE"),
    "The life of the Buddha predates Alexander's campaigns by about two centuries.",
    "easy",
    "Ancient",
    "India",
  ),
  question(
    "tr-014",
    e("Cyrus the Great founds the Achaemenid Empire", -550, "c. 550 BCE"),
    e("The Greco-Persian Wars begin", -499, "499 BCE"),
    "Persia's imperial rise came before its major wars with the Greek city-states.",
    "easy",
    "Ancient",
    "Ancient Near East",
  ),
  question(
    "tr-015",
    e("Cleisthenes reforms Athenian democracy", -508, "508 BCE"),
    e("The Battle of Marathon is fought", -490, "490 BCE"),
    "Athenian democratic reforms preceded the famous Greek victory at Marathon.",
    "medium",
    "Ancient",
    "Greece and Rome",
  ),
  question(
    "tr-016",
    e("The Battle of Thermopylae is fought", -480, "480 BCE"),
    e("The Peloponnesian War begins", -431, "431 BCE"),
    "Thermopylae was part of the Persian Wars, decades before Athens and Sparta fought each other.",
    "easy",
    "Ancient",
    "Greece and Rome",
  ),
  question(
    "tr-017",
    e("Socrates is executed in Athens", -399, "399 BCE"),
    e("Alexander the Great becomes king of Macedon", -336, "336 BCE"),
    "Socrates died before Alexander's conquests reshaped the eastern Mediterranean.",
    "medium",
    "Ancient",
    "Greece and Rome",
  ),
  question(
    "tr-018",
    e("Chandragupta Maurya founds the Maurya Empire", -322, "322 BCE"),
    e("Ashoka converts after the Kalinga War", -261, "c. 261 BCE"),
    "Chandragupta founded the empire that Ashoka later inherited and expanded.",
    "medium",
    "Ancient",
    "India",
  ),
  question(
    "tr-019",
    e("The Library of Alexandria is founded", -283, "c. 283 BCE"),
    e("The Rosetta Stone is carved", -196, "196 BCE"),
    "Alexandria's great library was created before the Ptolemaic decree preserved on the Rosetta Stone.",
    "hard",
    "Ancient",
    "Egypt",
  ),
  question(
    "tr-020",
    e("Qin Shi Huang unifies China", -221, "221 BCE"),
    e("The Han dynasty begins", -202, "202 BCE"),
    "Qin unification came first; the Han dynasty followed after Qin collapse.",
    "easy",
    "Ancient",
    "China",
  ),
  question(
    "tr-021",
    e("The Second Punic War begins", -218, "218 BCE"),
    e("Rome destroys Carthage", -146, "146 BCE"),
    "Hannibal's war with Rome happened before Carthage was finally destroyed in the Third Punic War.",
    "easy",
    "Ancient",
    "Greece and Rome",
  ),
  question(
    "tr-022",
    e("The Maccabean Revolt begins", -167, "167 BCE"),
    e("Julius Caesar crosses the Rubicon", -49, "49 BCE"),
    "The Maccabean Revolt belongs to the Hellenistic era, more than a century before Caesar's civil war.",
    "hard",
    "Ancient",
    "Ancient Near East",
  ),
  question(
    "tr-023",
    e("Sima Qian completes the Records of the Grand Historian", -91, "c. 91 BCE"),
    e("The Roman Empire begins under Augustus", -27, "27 BCE"),
    "Sima Qian's history was completed during Han China before Augustus became Rome's first emperor.",
    "hard",
    "Ancient",
    "China",
  ),
  question(
    "tr-024",
    e("Julius Caesar is assassinated", -44, "44 BCE"),
    e("The Battle of Actium is fought", -31, "31 BCE"),
    "Caesar's assassination set off the power struggle that later ended at Actium.",
    "easy",
    "Ancient",
    "Greece and Rome",
  ),
  question(
    "tr-025",
    e("The Roman Empire begins under Augustus", -27, "27 BCE"),
    e("Pompeii is buried by Vesuvius", 79, "79 CE"),
    "Augustus founded the imperial system more than a century before Vesuvius buried Pompeii.",
    "easy",
    "Classical",
    "Greece and Rome",
  ),
  question(
    "tr-026",
    e("Jesus of Nazareth is crucified", 30, "c. 30 CE"),
    e("The First Jewish-Roman War begins", 66, "66 CE"),
    "The crucifixion came decades before rebellion broke out against Roman rule in Judea.",
    "medium",
    "Classical",
    "Ancient Near East",
  ),
  question(
    "tr-027",
    e("The Han dynasty falls", 220, "220 CE"),
    e("Constantine founds Constantinople", 330, "330 CE"),
    "Han China fractured before Constantine established his new imperial capital.",
    "medium",
    "Classical",
    "China",
  ),
  question(
    "tr-028",
    e("The Gupta Empire begins in northern India", 320, "c. 320 CE"),
    e("The Western Roman Empire falls", 476, "476 CE"),
    "The Gupta age began before the traditional fall of the Western Roman Empire.",
    "medium",
    "Classical",
    "India",
  ),
  question(
    "tr-029",
    e("The Council of Nicaea is held", 325, "325 CE"),
    e("The Huns invade Gaul", 451, "451 CE"),
    "Nicaea was an early Christian imperial council, well before Attila's western campaigns.",
    "medium",
    "Classical",
    "Europe",
  ),
  question(
    "tr-030",
    e("Aksum adopts Christianity under King Ezana", 330, "c. 330 CE"),
    e("Islam begins in Arabia", 610, "610 CE"),
    "Aksum became a Christian kingdom centuries before the emergence of Islam.",
    "medium",
    "Classical",
    "Africa",
  ),
  question(
    "tr-031",
    e("The Western Roman Empire falls", 476, "476 CE"),
    e("Justinian begins his reign", 527, "527 CE"),
    "The western empire fell before Justinian's Byzantine reconquests.",
    "easy",
    "Classical",
    "Europe",
  ),
  question(
    "tr-032",
    e("The Sui dynasty reunifies China", 589, "589 CE"),
    e("The Tang dynasty begins", 618, "618 CE"),
    "The short-lived Sui reunified China before the Tang dynasty took power.",
    "medium",
    "Medieval",
    "China",
  ),
  question(
    "tr-033",
    e("Muhammad receives the first revelations", 610, "610 CE"),
    e("The Hijra to Medina takes place", 622, "622 CE"),
    "The first revelations preceded the migration to Medina that marks the Islamic calendar's start.",
    "easy",
    "Medieval",
    "Islamic world",
  ),
  question(
    "tr-034",
    e("The Battle of Yarmouk is fought", 636, "636 CE"),
    e("The Umayyad Caliphate begins", 661, "661 CE"),
    "Arab-Muslim forces defeated Byzantium at Yarmouk before the Umayyads founded their dynasty.",
    "medium",
    "Medieval",
    "Islamic world",
  ),
  question(
    "tr-035",
    e("The Umayyad conquest of Hispania begins", 711, "711 CE"),
    e("The Abbasid Revolution overthrows the Umayyads", 750, "750 CE"),
    "Muslim armies entered Iberia before the Abbasids replaced the Umayyad caliphs in the east.",
    "medium",
    "Medieval",
    "Islamic world",
  ),
  question(
    "tr-036",
    e("The Battle of Talas is fought", 751, "751 CE"),
    e("Charlemagne is crowned emperor", 800, "800 CE"),
    "Talas, between Abbasid and Tang forces, came before Charlemagne's imperial coronation.",
    "hard",
    "Medieval",
    "Central Asia",
  ),
  question(
    "tr-037",
    e("Charlemagne is crowned emperor", 800, "800 CE"),
    e("The Treaty of Verdun divides his empire", 843, "843 CE"),
    "Charlemagne's coronation came before his grandsons divided the empire.",
    "easy",
    "Medieval",
    "Europe",
  ),
  question(
    "tr-038",
    e("The Khmer Empire begins its Angkor period", 802, "802 CE"),
    e("Angkor Wat is built", 1150, "c. 1150 CE"),
    "The Angkorian state began centuries before Angkor Wat was constructed.",
    "medium",
    "Medieval",
    "Southeast Asia",
  ),
  question(
    "tr-039",
    e("The Ghana Empire reaches prominence", 900, "c. 900 CE"),
    e("Mali's Sundiata Keita rises to power", 1235, "c. 1235 CE"),
    "Ghana was an earlier West African power before Mali's rise.",
    "medium",
    "Medieval",
    "Africa",
  ),
  question(
    "tr-040",
    e("The Song dynasty begins", 960, "960 CE"),
    e("The Norman conquest of England occurs", 1066, "1066 CE"),
    "Song China began more than a century before William conquered England.",
    "medium",
    "Medieval",
    "China",
  ),
  question(
    "tr-041",
    e("The Seljuk Turks defeat Byzantium at Manzikert", 1071, "1071 CE"),
    e("The First Crusade captures Jerusalem", 1099, "1099 CE"),
    "Manzikert helped shift power in Anatolia before crusader armies captured Jerusalem.",
    "medium",
    "Medieval",
    "Islamic world",
  ),
  question(
    "tr-042",
    e("The University of Bologna is founded", 1088, "1088 CE"),
    e("The Magna Carta is sealed", 1215, "1215 CE"),
    "Bologna's university predates Magna Carta by more than a century.",
    "hard",
    "Medieval",
    "Europe",
  ),
  question(
    "tr-043",
    e("The Inca state begins around Cusco", 1200, "c. 1200 CE"),
    e("The Aztec Triple Alliance forms", 1428, "1428 CE"),
    "The Inca polity began before the Aztec imperial alliance formed.",
    "medium",
    "Medieval",
    "Americas",
  ),
  question(
    "tr-044",
    e("Genghis Khan is proclaimed ruler of the Mongols", 1206, "1206 CE"),
    e("The Mongols sack Baghdad", 1258, "1258 CE"),
    "Genghis Khan unified the Mongols before later Mongol armies destroyed Abbasid Baghdad.",
    "easy",
    "Medieval",
    "Central Asia",
  ),
  question(
    "tr-045",
    e("The Delhi Sultanate is founded", 1206, "1206 CE"),
    e("The Mughal Empire is founded", 1526, "1526 CE"),
    "The Delhi Sultanate came centuries before Babur founded the Mughal Empire.",
    "easy",
    "Medieval",
    "India",
  ),
  question(
    "tr-046",
    e("The Mali Empire rises under Sundiata Keita", 1235, "c. 1235 CE"),
    e("Mansa Musa makes his pilgrimage to Mecca", 1324, "1324 CE"),
    "Sundiata's rise created the empire that Mansa Musa later ruled.",
    "easy",
    "Medieval",
    "Africa",
  ),
  question(
    "tr-047",
    e("Kublai Khan founds the Yuan dynasty", 1271, "1271 CE"),
    e("The Ming dynasty begins", 1368, "1368 CE"),
    "The Mongol Yuan dynasty ruled China before the Ming overthrew it.",
    "easy",
    "Medieval",
    "China",
  ),
  question(
    "tr-048",
    e("The Black Death reaches Europe", 1347, "1347 CE"),
    e("The Ming dynasty begins", 1368, "1368 CE"),
    "The plague devastated Europe before the Ming dynasty replaced Yuan rule in China.",
    "medium",
    "Medieval",
    "Global",
  ),
  question(
    "tr-049",
    e("The Ottoman capture of Constantinople", 1453, "1453 CE"),
    e("Columbus reaches the Caribbean", 1492, "1492 CE"),
    "Constantinople fell to the Ottomans decades before Columbus's Atlantic voyage.",
    "easy",
    "Early modern",
    "Europe",
  ),
  question(
    "tr-050",
    e("The Songhai Empire captures Timbuktu", 1468, "1468 CE"),
    e("Portugal reaches India by sea", 1498, "1498 CE"),
    "Songhai expansion in West Africa came before Vasco da Gama's voyage to India.",
    "medium",
    "Early modern",
    "Africa",
  ),
  question(
    "tr-051",
    e("Columbus reaches the Caribbean", 1492, "1492 CE"),
    e("The Aztec capital Tenochtitlan falls", 1521, "1521 CE"),
    "Columbus's first voyage preceded the Spanish conquest of the Aztec capital.",
    "easy",
    "Early modern",
    "Americas",
  ),
  question(
    "tr-052",
    e("Vasco da Gama reaches India by sea", 1498, "1498 CE"),
    e("Magellan's expedition completes the first circumnavigation", 1522, "1522 CE"),
    "Da Gama opened the sea route to India before Magellan's expedition circumnavigated the globe.",
    "easy",
    "Early modern",
    "Global",
  ),
  question(
    "tr-053",
    e("The Safavid Empire is founded in Iran", 1501, "1501 CE"),
    e("The Mughal Empire is founded in India", 1526, "1526 CE"),
    "The Safavids founded their Persian empire before Babur founded Mughal rule in India.",
    "medium",
    "Early modern",
    "Islamic world",
  ),
  question(
    "tr-054",
    e("Martin Luther posts the Ninety-Five Theses", 1517, "1517 CE"),
    e("The Council of Trent begins", 1545, "1545 CE"),
    "Luther's protest helped spark the Reformation before the Catholic reform council opened.",
    "easy",
    "Early modern",
    "Europe",
  ),
  question(
    "tr-055",
    e("Tenochtitlan falls to Spanish forces", 1521, "1521 CE"),
    e("Pizarro captures Atahualpa", 1532, "1532 CE"),
    "The Aztec capital fell before the Spanish conquest of the Inca Empire accelerated.",
    "easy",
    "Early modern",
    "Americas",
  ),
  question(
    "tr-056",
    e("The Mughal Empire is founded", 1526, "1526 CE"),
    e("Akbar begins his reign", 1556, "1556 CE"),
    "Babur founded Mughal power before Akbar's long imperial reign.",
    "easy",
    "Early modern",
    "India",
  ),
  question(
    "tr-057",
    e("The Spanish found Manila", 1571, "1571 CE"),
    e("The Dutch East India Company is founded", 1602, "1602 CE"),
    "Spanish colonial Manila became a Pacific trade hub before the VOC was chartered.",
    "medium",
    "Early modern",
    "Southeast Asia",
  ),
  question(
    "tr-058",
    e("The Spanish Armada is defeated", 1588, "1588 CE"),
    e("Tokugawa Ieyasu wins at Sekigahara", 1600, "1600 CE"),
    "England's defeat of the Armada came before Tokugawa power was secured in Japan.",
    "medium",
    "Early modern",
    "Global",
  ),
  question(
    "tr-059",
    e("Tokugawa Ieyasu establishes the shogunate", 1603, "1603 CE"),
    e("The Thirty Years' War begins", 1618, "1618 CE"),
    "Tokugawa rule began in Japan before Europe's Thirty Years' War.",
    "medium",
    "Early modern",
    "Asia",
  ),
  question(
    "tr-060",
    e("The Mayflower arrives in Plymouth", 1620, "1620 CE"),
    e("The Qing dynasty captures Beijing", 1644, "1644 CE"),
    "The Plymouth colony began before the Qing took Beijing and ruled China.",
    "medium",
    "Early modern",
    "Global",
  ),
  question(
    "tr-061",
    e("The Taj Mahal is completed", 1653, "1653 CE"),
    e("The Glorious Revolution occurs", 1688, "1688 CE"),
    "The Mughal monument was completed before England's Glorious Revolution.",
    "medium",
    "Early modern",
    "Global",
  ),
  question(
    "tr-062",
    e("The Kangxi Emperor begins his reign", 1661, "1661 CE"),
    e("Peter the Great founds Saint Petersburg", 1703, "1703 CE"),
    "Kangxi's long Qing reign began decades before Peter founded Saint Petersburg.",
    "hard",
    "Early modern",
    "China",
  ),
  question(
    "tr-063",
    e("The Asante Kingdom is founded", 1670, "c. 1670 CE"),
    e("The Haitian Revolution begins", 1791, "1791 CE"),
    "Asante state formation in West Africa came before the Haitian Revolution.",
    "medium",
    "Early modern",
    "Africa",
  ),
  question(
    "tr-064",
    e("The Treaty of Utrecht is signed", 1713, "1713 CE"),
    e("The Seven Years' War begins", 1756, "1756 CE"),
    "Utrecht ended earlier European wars before the Seven Years' War reshaped global empires.",
    "medium",
    "Early modern",
    "Europe",
  ),
  question(
    "tr-065",
    e("The Qianlong Emperor begins his reign", 1735, "1735 CE"),
    e("The American Declaration of Independence is adopted", 1776, "1776 CE"),
    "Qianlong was already ruling Qing China before the American colonies declared independence.",
    "medium",
    "Early modern",
    "China",
  ),
  question(
    "tr-066",
    e("The Seven Years' War ends", 1763, "1763 CE"),
    e("The Boston Tea Party takes place", 1773, "1773 CE"),
    "The imperial settlement after the Seven Years' War preceded tensions that led to the Boston Tea Party.",
    "easy",
    "Early modern",
    "Americas",
  ),
  question(
    "tr-067",
    e("The American Declaration of Independence", 1776, "1776 CE"),
    e("The French Revolution begins", 1789, "1789 CE"),
    "American independence came before the French Revolution.",
    "easy",
    "Modern",
    "Americas",
  ),
  question(
    "tr-068",
    e("The Haitian Revolution begins", 1791, "1791 CE"),
    e("Napoleon crowns himself emperor", 1804, "1804 CE"),
    "The Haitian Revolution began before Napoleon created the French Empire.",
    "easy",
    "Modern",
    "Americas",
  ),
  question(
    "tr-069",
    e("The Rosetta Stone is found", 1799, "1799 CE"),
    e("The Battle of Trafalgar is fought", 1805, "1805 CE"),
    "The Rosetta Stone was discovered during Napoleon's Egypt campaign before Trafalgar.",
    "medium",
    "Modern",
    "Egypt",
  ),
  question(
    "tr-070",
    e("The Louisiana Purchase is completed", 1803, "1803 CE"),
    e("The Congress of Vienna opens", 1814, "1814 CE"),
    "The United States bought Louisiana before European powers met after Napoleon's defeat.",
    "medium",
    "Modern",
    "Global",
  ),
  question(
    "tr-071",
    e("The Haitian Republic declares independence", 1804, "1804 CE"),
    e("Bolivar begins the Admirable Campaign", 1813, "1813 CE"),
    "Haiti became independent before Bolivar's major campaigns in northern South America.",
    "medium",
    "Modern",
    "Americas",
  ),
  question(
    "tr-072",
    e("The Battle of Waterloo is fought", 1815, "1815 CE"),
    e("Brazil declares independence from Portugal", 1822, "1822 CE"),
    "Napoleon's final defeat came before Brazil's independence.",
    "easy",
    "Modern",
    "Europe",
  ),
  question(
    "tr-073",
    e("The Monroe Doctrine is announced", 1823, "1823 CE"),
    e("The First Opium War begins", 1839, "1839 CE"),
    "The Monroe Doctrine came before Britain's first war with Qing China over opium and trade.",
    "medium",
    "Modern",
    "Global",
  ),
  question(
    "tr-074",
    e("Greece gains independence recognition", 1830, "1830 CE"),
    e("The Revolutions of 1848 begin", 1848, "1848 CE"),
    "Greek independence was recognized before the wave of 1848 revolutions.",
    "medium",
    "Modern",
    "Europe",
  ),
  question(
    "tr-075",
    e("The First Opium War begins", 1839, "1839 CE"),
    e("The Taiping Rebellion begins", 1850, "1850 CE"),
    "The Opium War preceded the massive Taiping civil war in Qing China.",
    "easy",
    "Modern",
    "China",
  ),
  question(
    "tr-076",
    e("The Treaty of Waitangi is signed", 1840, "1840 CE"),
    e("The Meiji Restoration begins", 1868, "1868 CE"),
    "New Zealand's treaty with Britain came before Japan's Meiji Restoration.",
    "medium",
    "Modern",
    "Oceania",
  ),
  question(
    "tr-077",
    e("The Communist Manifesto is published", 1848, "1848 CE"),
    e("The Sepoy Rebellion begins", 1857, "1857 CE"),
    "Marx and Engels published their manifesto before the uprising against Company rule in India.",
    "medium",
    "Modern",
    "Global",
  ),
  question(
    "tr-078",
    e("The Crimean War begins", 1853, "1853 CE"),
    e("The American Civil War begins", 1861, "1861 CE"),
    "The Crimean War came before the American Civil War.",
    "easy",
    "Modern",
    "Global",
  ),
  question(
    "tr-079",
    e("The Indian Rebellion begins", 1857, "1857 CE"),
    e("The Suez Canal opens", 1869, "1869 CE"),
    "The rebellion against British East India Company rule came before the Suez Canal opened.",
    "easy",
    "Modern",
    "India",
  ),
  question(
    "tr-080",
    e("Italy is unified as a kingdom", 1861, "1861 CE"),
    e("Germany is unified as an empire", 1871, "1871 CE"),
    "Italy's kingdom was proclaimed a decade before German unification.",
    "easy",
    "Modern",
    "Europe",
  ),
  question(
    "tr-081",
    e("The Meiji Restoration begins", 1868, "1868 CE"),
    e("The Berlin Conference begins", 1884, "1884 CE"),
    "Japan's Meiji Restoration came before European powers formalized the Scramble for Africa.",
    "medium",
    "Modern",
    "Asia",
  ),
  question(
    "tr-082",
    e("The Suez Canal opens", 1869, "1869 CE"),
    e("The Mahdist Revolt begins in Sudan", 1881, "1881 CE"),
    "The canal opened before the Mahdist movement challenged Egyptian and British power in Sudan.",
    "medium",
    "Modern",
    "Africa",
  ),
  question(
    "tr-083",
    e("The Battle of Little Bighorn is fought", 1876, "1876 CE"),
    e("The Zulu victory at Isandlwana", 1879, "1879 CE"),
    "Little Bighorn came three years before Zulu forces defeated the British at Isandlwana.",
    "hard",
    "Modern",
    "Global",
  ),
  question(
    "tr-084",
    e("The Berlin Conference begins", 1884, "1884 CE"),
    e("The First Italo-Ethiopian War begins", 1895, "1895 CE"),
    "The Berlin Conference came before Ethiopia's successful resistance to Italy at Adwa.",
    "medium",
    "Modern",
    "Africa",
  ),
  question(
    "tr-085",
    e("The Wounded Knee massacre occurs", 1890, "1890 CE"),
    e("The Spanish-American War begins", 1898, "1898 CE"),
    "Wounded Knee came before the United States fought Spain and gained overseas territories.",
    "medium",
    "Modern",
    "Americas",
  ),
  question(
    "tr-086",
    e("Japan defeats China in the First Sino-Japanese War", 1895, "1895 CE"),
    e("The Boxer Rebellion begins", 1899, "1899 CE"),
    "Japan's victory over Qing China came before the anti-foreign Boxer uprising.",
    "medium",
    "Modern",
    "East Asia",
  ),
  question(
    "tr-087",
    e("The Battle of Adwa is fought", 1896, "1896 CE"),
    e("The Boer War begins", 1899, "1899 CE"),
    "Ethiopia defeated Italy at Adwa before war broke out between Britain and the Boer republics.",
    "medium",
    "Modern",
    "Africa",
  ),
  question(
    "tr-088",
    e("The Philippine-American War begins", 1899, "1899 CE"),
    e("The Wright brothers fly at Kitty Hawk", 1903, "1903 CE"),
    "War in the Philippines began before the first powered airplane flight.",
    "medium",
    "Modern",
    "Global",
  ),
  question(
    "tr-089",
    e("The Boxer Rebellion begins", 1899, "1899 CE"),
    e("The Russo-Japanese War begins", 1904, "1904 CE"),
    "The Boxer crisis came before Japan and Russia fought over influence in East Asia.",
    "medium",
    "Modern",
    "China",
  ),
  question(
    "tr-090",
    e("The Russo-Japanese War begins", 1904, "1904 CE"),
    e("The Mexican Revolution begins", 1910, "1910 CE"),
    "Japan and Russia went to war before revolution erupted in Mexico.",
    "easy",
    "Modern",
    "Global",
  ),
  question(
    "tr-091",
    e("The Young Turk Revolution occurs", 1908, "1908 CE"),
    e("World War I begins", 1914, "1914 CE"),
    "The Young Turk Revolution preceded the Ottoman Empire's entry into the First World War era.",
    "medium",
    "Modern",
    "Islamic world",
  ),
  question(
    "tr-092",
    e("The Chinese Revolution topples the Qing", 1911, "1911 CE"),
    e("The Russian Revolution begins", 1917, "1917 CE"),
    "China's Qing dynasty fell before Russia's Romanov dynasty did.",
    "easy",
    "Modern",
    "China",
  ),
  question(
    "tr-093",
    e("World War I begins", 1914, "1914 CE"),
    e("The Armenian Genocide begins", 1915, "1915 CE"),
    "The First World War began before the Ottoman deportations and massacres of Armenians escalated.",
    "medium",
    "World wars",
    "Global",
  ),
  question(
    "tr-094",
    e("The Easter Rising occurs in Ireland", 1916, "1916 CE"),
    e("The Balfour Declaration is issued", 1917, "1917 CE"),
    "The Easter Rising came one year before Britain's Balfour Declaration.",
    "hard",
    "World wars",
    "Europe",
  ),
  question(
    "tr-095",
    e("The Russian Revolution begins", 1917, "1917 CE"),
    e("The Treaty of Versailles is signed", 1919, "1919 CE"),
    "Russia's revolutions occurred before the peace treaty that ended the war with Germany.",
    "easy",
    "World wars",
    "Europe",
  ),
  question(
    "tr-096",
    e("The May Fourth Movement begins", 1919, "1919 CE"),
    e("The Chinese Communist Party is founded", 1921, "1921 CE"),
    "Student protests in 1919 helped shape the intellectual world from which the CCP soon emerged.",
    "medium",
    "Modern",
    "China",
  ),
  question(
    "tr-097",
    e("The Turkish Republic is proclaimed", 1923, "1923 CE"),
    e("The Indian National Congress launches the Salt March", 1930, "1930 CE"),
    "Modern Turkey was founded before Gandhi's Salt March challenged British rule.",
    "medium",
    "Modern",
    "Global",
  ),
  question(
    "tr-098",
    e("The Great Depression begins", 1929, "1929 CE"),
    e("Hitler becomes German chancellor", 1933, "1933 CE"),
    "The global economic crisis began before Hitler came to power.",
    "easy",
    "Modern",
    "Global",
  ),
  question(
    "tr-099",
    e("Japan invades Manchuria", 1931, "1931 CE"),
    e("The Second Italo-Ethiopian War begins", 1935, "1935 CE"),
    "Japan's seizure of Manchuria came before Mussolini's invasion of Ethiopia.",
    "medium",
    "World wars",
    "Global",
  ),
  question(
    "tr-100",
    e("The Long March begins in China", 1934, "1934 CE"),
    e("The Spanish Civil War begins", 1936, "1936 CE"),
    "The Chinese Communist retreat began before Spain's civil war.",
    "medium",
    "Modern",
    "Global",
  ),
  question(
    "tr-101",
    e("World War II begins in Europe", 1939, "1939 CE"),
    e("Japan attacks Pearl Harbor", 1941, "1941 CE"),
    "The war in Europe began before Pearl Harbor brought the United States directly into the conflict.",
    "easy",
    "World wars",
    "Global",
  ),
  question(
    "tr-102",
    e("The Battle of Britain begins", 1940, "1940 CE"),
    e("Operation Barbarossa begins", 1941, "1941 CE"),
    "Germany attacked Britain from the air before invading the Soviet Union.",
    "easy",
    "World wars",
    "Europe",
  ),
  question(
    "tr-103",
    e("The Quit India Movement begins", 1942, "1942 CE"),
    e("D-Day landings take place", 1944, "1944 CE"),
    "India's mass anti-colonial campaign began before Allied troops landed in Normandy.",
    "medium",
    "World wars",
    "India",
  ),
  question(
    "tr-104",
    e("The Battle of Stalingrad ends", 1943, "1943 CE"),
    e("The atomic bombing of Hiroshima", 1945, "1945 CE"),
    "Stalingrad ended before the final year of the Pacific War and the bombing of Hiroshima.",
    "easy",
    "World wars",
    "Global",
  ),
  question(
    "tr-105",
    e("The United Nations is founded", 1945, "1945 CE"),
    e("India and Pakistan become independent", 1947, "1947 CE"),
    "The UN was founded at the end of World War II before South Asian independence and partition.",
    "easy",
    "Decolonization",
    "Global",
  ),
  question(
    "tr-106",
    e("The Marshall Plan is announced", 1947, "1947 CE"),
    e("NATO is founded", 1949, "1949 CE"),
    "US economic reconstruction plans came before the formal North Atlantic alliance.",
    "easy",
    "Cold War",
    "Europe",
  ),
  question(
    "tr-107",
    e("The People's Republic of China is proclaimed", 1949, "1949 CE"),
    e("The Korean War begins", 1950, "1950 CE"),
    "The PRC was founded shortly before war broke out in Korea.",
    "easy",
    "Cold War",
    "East Asia",
  ),
  question(
    "tr-108",
    e("Ghana becomes independent", 1957, "1957 CE"),
    e("Nigeria becomes independent", 1960, "1960 CE"),
    "Ghana was the first sub-Saharan African colony to gain independence in this wave, before Nigeria.",
    "easy",
    "Decolonization",
    "Africa",
  ),
  question(
    "tr-109",
    e("The Cuban Revolution succeeds", 1959, "1959 CE"),
    e("The Berlin Wall is built", 1961, "1961 CE"),
    "Castro's revolution took power before the Berlin Wall divided the city.",
    "easy",
    "Cold War",
    "Americas",
  ),
  question(
    "tr-110",
    e("The Congo Crisis begins", 1960, "1960 CE"),
    e("The Cuban Missile Crisis occurs", 1962, "1962 CE"),
    "Congo's post-independence crisis began before the superpower nuclear standoff over Cuba.",
    "medium",
    "Cold War",
    "Global",
  ),
  question(
    "tr-111",
    e("Algeria gains independence", 1962, "1962 CE"),
    e("Kenya gains independence", 1963, "1963 CE"),
    "Algeria's war of independence ended before Kenya became independent.",
    "medium",
    "Decolonization",
    "Africa",
  ),
  question(
    "tr-112",
    e("The March on Washington takes place", 1963, "1963 CE"),
    e("The Cultural Revolution begins", 1966, "1966 CE"),
    "The civil rights march in Washington came before Mao launched the Cultural Revolution.",
    "medium",
    "Modern",
    "Global",
  ),
  question(
    "tr-113",
    e("Singapore becomes independent", 1965, "1965 CE"),
    e("ASEAN is founded", 1967, "1967 CE"),
    "Singapore became an independent state before it joined other countries in founding ASEAN.",
    "easy",
    "Decolonization",
    "Southeast Asia",
  ),
  question(
    "tr-114",
    e("The Six-Day War is fought", 1967, "1967 CE"),
    e("The Apollo 11 Moon landing", 1969, "1969 CE"),
    "The Arab-Israeli Six-Day War happened before humans landed on the Moon.",
    "easy",
    "Cold War",
    "Global",
  ),
  question(
    "tr-115",
    e("Bangladesh declares independence", 1971, "1971 CE"),
    e("The Yom Kippur War begins", 1973, "1973 CE"),
    "Bangladesh's independence war came before the 1973 Middle East war.",
    "medium",
    "Modern",
    "Asia",
  ),
  question(
    "tr-116",
    e("The Helsinki Accords are signed", 1975, "1975 CE"),
    e("The Iranian Revolution succeeds", 1979, "1979 CE"),
    "The Cold War Helsinki agreement came before Iran's monarchy fell.",
    "medium",
    "Cold War",
    "Global",
  ),
  question(
    "tr-117",
    e("Vietnam is reunified", 1976, "1976 CE"),
    e("The Soviet invasion of Afghanistan begins", 1979, "1979 CE"),
    "Vietnam's reunification came before the Soviet-Afghan War.",
    "medium",
    "Cold War",
    "Asia",
  ),
  question(
    "tr-118",
    e("The Camp David Accords are signed", 1978, "1978 CE"),
    e("The Iran-Iraq War begins", 1980, "1980 CE"),
    "Egypt and Israel reached Camp David before Iran and Iraq went to war.",
    "easy",
    "Modern",
    "Islamic world",
  ),
  question(
    "tr-119",
    e("The Falklands War begins", 1982, "1982 CE"),
    e("The Chernobyl disaster occurs", 1986, "1986 CE"),
    "The South Atlantic war came before the nuclear disaster in Soviet Ukraine.",
    "easy",
    "Cold War",
    "Global",
  ),
  question(
    "tr-120",
    e("People Power Revolution in the Philippines", 1986, "1986 CE"),
    e("The fall of the Berlin Wall", 1989, "1989 CE"),
    "The overthrow of Ferdinand Marcos came before the Berlin Wall fell.",
    "medium",
    "Cold War",
    "Global",
  ),
  question(
    "tr-121",
    e("The Tiananmen Square crackdown occurs", 1989, "1989 CE"),
    e("Nelson Mandela is released from prison", 1990, "1990 CE"),
    "China's 1989 crackdown came before Mandela's release in South Africa.",
    "easy",
    "Contemporary",
    "Global",
  ),
  question(
    "tr-122",
    e("German reunification occurs", 1990, "1990 CE"),
    e("The Soviet Union dissolves", 1991, "1991 CE"),
    "Germany reunified before the Soviet Union formally dissolved.",
    "easy",
    "Cold War",
    "Europe",
  ),
  question(
    "tr-123",
    e("The Gulf War begins", 1991, "1991 CE"),
    e("The Oslo Accords are signed", 1993, "1993 CE"),
    "The US-led war to expel Iraq from Kuwait came before the Oslo peace process.",
    "medium",
    "Contemporary",
    "Islamic world",
  ),
  question(
    "tr-124",
    e("South Africa holds its first universal democratic election", 1994, "1994 CE"),
    e("The Rwandan genocide begins", 1994.3, "April 1994"),
    "South Africa's election and the Rwandan genocide both occurred in 1994, but Rwanda's genocide began in April before South Africa voted later that month.",
    "hard",
    "Contemporary",
    "Africa",
  ),
  question(
    "tr-125",
    e("The Good Friday Agreement is signed", 1998, "1998 CE"),
    e("The euro is introduced as electronic currency", 1999, "1999 CE"),
    "Northern Ireland's peace agreement came before the euro's first launch.",
    "medium",
    "Contemporary",
    "Europe",
  ),
  question(
    "tr-126",
    e("The 9/11 attacks occur", 2001, "2001 CE"),
    e("The Iraq War begins", 2003, "2003 CE"),
    "The September 11 attacks preceded the US-led invasion of Iraq.",
    "easy",
    "Contemporary",
    "Global",
  ),
  question(
    "tr-127",
    e("The Indian Ocean tsunami occurs", 2004, "2004 CE"),
    e("Hurricane Katrina strikes the Gulf Coast", 2005, "2005 CE"),
    "The Indian Ocean disaster came the year before Hurricane Katrina.",
    "easy",
    "Contemporary",
    "Global",
  ),
  question(
    "tr-128",
    e("Twitter is launched", 2006, "2006 CE"),
    e("The global financial crisis escalates", 2008, "2008 CE"),
    "Twitter launched before the 2008 financial crisis reshaped the world economy.",
    "medium",
    "Contemporary",
    "Global",
  ),
  question(
    "tr-129",
    e("The Arab Spring begins in Tunisia", 2010, "2010 CE"),
    e("South Sudan becomes independent", 2011, "2011 CE"),
    "Protests in Tunisia began before South Sudan became the world's newest state.",
    "easy",
    "Contemporary",
    "Africa",
  ),
  question(
    "tr-130",
    e("The Fukushima nuclear disaster occurs", 2011, "2011 CE"),
    e("Russia annexes Crimea", 2014, "2014 CE"),
    "Fukushima followed Japan's earthquake and tsunami before Russia's annexation of Crimea.",
    "easy",
    "Contemporary",
    "Global",
  ),
  question(
    "tr-131",
    e("The Paris Climate Agreement is adopted", 2015, "2015 CE"),
    e("The Brexit referendum is held", 2016, "2016 CE"),
    "The Paris climate deal was adopted before UK voters chose Brexit.",
    "easy",
    "Contemporary",
    "Global",
  ),
  question(
    "tr-132",
    e("The COVID-19 pandemic is declared by WHO", 2020, "2020 CE"),
    e("Russia launches its full-scale invasion of Ukraine", 2022, "2022 CE"),
    "The pandemic was declared before Russia's 2022 escalation in Ukraine.",
    "easy",
    "Contemporary",
    "Global",
  ),
  question(
    "tr-133",
    e("The Bronze Age Collapse begins", -1200, "c. 1200 BCE"),
    e("The Neo-Assyrian Empire reaches its height", -700, "c. 700 BCE"),
    "The disruptions of the Late Bronze Age came before Assyria's later imperial peak.",
    "medium",
    "Ancient",
    "Ancient Near East",
  ),
  question(
    "tr-134",
    e("The Lapita culture expands across the Pacific", -1500, "c. 1500 BCE"),
    e("Polynesians settle New Zealand", 1250, "c. 1250 CE"),
    "Early Pacific voyaging traditions long predated settlement of New Zealand.",
    "hard",
    "Ancient",
    "Oceania",
  ),
  question(
    "tr-135",
    e("The Chavin culture flourishes in the Andes", -900, "c. 900 BCE"),
    e("The Nazca Lines are created", 500, "c. 500 CE"),
    "Chavin was an early Andean civilization, long before the Nazca geoglyphs.",
    "medium",
    "Ancient",
    "South America",
  ),
  question(
    "tr-136",
    e("The Hopewell tradition flourishes in North America", 100, "c. 100 CE"),
    e("Cahokia reaches its peak", 1100, "c. 1100 CE"),
    "Hopewell ceremonial centers came about a millennium before Cahokia's urban peak.",
    "hard",
    "Classical",
    "Americas",
  ),
  question(
    "tr-137",
    e("Teotihuacan reaches its height", 450, "c. 450 CE"),
    e("Chichen Itza rises as a major Maya center", 900, "c. 900 CE"),
    "Teotihuacan's classic urban peak came before Chichen Itza's later prominence.",
    "medium",
    "Classical",
    "Mesoamerica",
  ),
  question(
    "tr-138",
    e("The Maya city of Tikal reaches a classic peak", 700, "c. 700 CE"),
    e("The Aztec Triple Alliance forms", 1428, "1428 CE"),
    "Classic Maya city-states flourished centuries before the Aztec Empire.",
    "easy",
    "Medieval",
    "Mesoamerica",
  ),
  question(
    "tr-139",
    e("Great Zimbabwe begins to flourish", 1200, "c. 1200 CE"),
    e("The Kingdom of Kongo is founded", 1390, "c. 1390 CE"),
    "Great Zimbabwe's stone-built trading center flourished before Kongo's rise in Central Africa.",
    "medium",
    "Medieval",
    "Africa",
  ),
  question(
    "tr-140",
    e("The Srivijaya empire dominates maritime trade", 700, "c. 700 CE"),
    e("Majapahit reaches its height", 1350, "c. 1350 CE"),
    "Srivijaya was the earlier Southeast Asian maritime power before Majapahit.",
    "medium",
    "Medieval",
    "Southeast Asia",
  ),
  question(
    "tr-141",
    e("The Fatimid Caliphate is founded", 909, "909 CE"),
    e("Saladin captures Jerusalem", 1187, "1187 CE"),
    "The Fatimid dynasty began before Saladin's Ayyubid forces retook Jerusalem.",
    "hard",
    "Medieval",
    "Islamic world",
  ),
  question(
    "tr-142",
    e("The Almoravid movement captures Marrakesh", 1062, "1062 CE"),
    e("Ibn Battuta begins his travels", 1325, "1325 CE"),
    "The Almoravid rise in North Africa preceded Ibn Battuta's fourteenth-century journeys.",
    "hard",
    "Medieval",
    "Islamic world",
  ),
  question(
    "tr-143",
    e("The Chola navy raids Srivijaya", 1025, "1025 CE"),
    e("The Delhi Sultanate is founded", 1206, "1206 CE"),
    "Chola expansion into Southeast Asia came before the founding of the Delhi Sultanate.",
    "hard",
    "Medieval",
    "India",
  ),
  question(
    "tr-144",
    e("The printing of the Gutenberg Bible", 1455, "c. 1455 CE"),
    e("The Protestant Reformation begins", 1517, "1517 CE"),
    "Movable-type printing in Europe preceded the rapid spread of Reformation writings.",
    "easy",
    "Early modern",
    "Europe",
  ),
  question(
    "tr-145",
    e("The Portuguese capture Malacca", 1511, "1511 CE"),
    e("The Spanish found Manila", 1571, "1571 CE"),
    "Portugal seized Malacca before Spain established Manila as a colonial capital.",
    "medium",
    "Early modern",
    "Southeast Asia",
  ),
  question(
    "tr-146",
    e("The Battle of Lepanto is fought", 1571, "1571 CE"),
    e("The Thirty Years' War begins", 1618, "1618 CE"),
    "The Mediterranean battle at Lepanto came before the continental Thirty Years' War.",
    "medium",
    "Early modern",
    "Europe",
  ),
  question(
    "tr-147",
    e("The Pueblo Revolt begins", 1680, "1680 CE"),
    e("The Haitian Revolution begins", 1791, "1791 CE"),
    "Indigenous revolt in New Mexico came more than a century before the Haitian Revolution.",
    "hard",
    "Early modern",
    "Americas",
  ),
  question(
    "tr-148",
    e("The Battle of Plassey is fought", 1757, "1757 CE"),
    e("The American Revolution begins", 1775, "1775 CE"),
    "The East India Company's victory in Bengal came before open war in Britain's North American colonies.",
    "medium",
    "Early modern",
    "Global",
  ),
  question(
    "tr-149",
    e("The Zulu Kingdom rises under Shaka", 1816, "c. 1816 CE"),
    e("The Battle of Isandlwana is fought", 1879, "1879 CE"),
    "Shaka's state-building came decades before the Anglo-Zulu War.",
    "medium",
    "Modern",
    "Africa",
  ),
  question(
    "tr-150",
    e("The Greek War of Independence begins", 1821, "1821 CE"),
    e("The Indian National Congress is founded", 1885, "1885 CE"),
    "Greek independence efforts began well before organized Indian nationalist politics emerged.",
    "medium",
    "Modern",
    "Global",
  ),
  question(
    "tr-151",
    e("The Paraguayan War begins", 1864, "1864 CE"),
    e("The War of the Pacific begins", 1879, "1879 CE"),
    "South America's devastating Paraguayan War began before the later Chile-Peru-Bolivia conflict.",
    "hard",
    "Modern",
    "South America",
  ),
  question(
    "tr-152",
    e("The Xinhai Revolution begins", 1911, "1911 CE"),
    e("The May Fourth Movement begins", 1919, "1919 CE"),
    "China's republican revolution came before the student-led May Fourth Movement.",
    "medium",
    "Modern",
    "China",
  ),
  question(
    "tr-153",
    e("The Mexican Constitution is adopted", 1917, "1917 CE"),
    e("The Egyptian Revolution of 1919 begins", 1919, "1919 CE"),
    "Mexico's revolutionary constitution came before Egypt's nationalist uprising against British rule.",
    "hard",
    "Modern",
    "Global",
  ),
  question(
    "tr-154",
    e("Indonesia declares independence", 1945, "1945 CE"),
    e("Vietnam declares independence", 1945.7, "September 1945"),
    "Indonesia's proclamation in August 1945 came shortly before Ho Chi Minh declared Vietnamese independence in September.",
    "hard",
    "Decolonization",
    "Southeast Asia",
  ),
  question(
    "tr-155",
    e("The Bandung Conference is held", 1955, "1955 CE"),
    e("The Non-Aligned Movement is founded", 1961, "1961 CE"),
    "Bandung helped inspire Afro-Asian solidarity before the formal Non-Aligned Movement.",
    "medium",
    "Decolonization",
    "Global",
  ),
  question(
    "tr-156",
    e("The Suez Crisis occurs", 1956, "1956 CE"),
    e("The Algerian War ends", 1962, "1962 CE"),
    "The Suez Crisis came before Algeria won independence from France.",
    "easy",
    "Decolonization",
    "Africa",
  ),
  question(
    "tr-157",
    e("The Prague Spring begins", 1968, "1968 CE"),
    e("Chile's military coup occurs", 1973, "1973 CE"),
    "Czechoslovakia's reform movement came before the coup against Salvador Allende.",
    "medium",
    "Cold War",
    "Global",
  ),
  question(
    "tr-158",
    e("Zimbabwe gains independence", 1980, "1980 CE"),
    e("Namibia gains independence", 1990, "1990 CE"),
    "Zimbabwe became independent a decade before Namibia.",
    "easy",
    "Decolonization",
    "Africa",
  ),
  question(
    "tr-159",
    e("The World Wide Web becomes publicly available", 1991, "1991 CE"),
    e("The Kyoto Protocol is adopted", 1997, "1997 CE"),
    "The web opened to public use before the major Kyoto climate agreement.",
    "medium",
    "Contemporary",
    "Global",
  ),
  question(
    "tr-160",
    e("The African Union is launched", 2002, "2002 CE"),
    e("Facebook launches", 2004, "2004 CE"),
    "The African Union replaced the OAU before Facebook began.",
    "medium",
    "Contemporary",
    "Africa",
  ),
];
